// _app.js file in Page Router
// Wraps Home Page

import React from 'react';
import "bootstrap/dist/css/bootstrap.min.css";
// import "./globals.css";
import { AntdRegistry } from '@ant-design/nextjs-registry';
import { ToastContainer } from "react-toastify";
import "react-toastify/dist/ReactToastify.css";
import TopNav from "../components/TopNav";
import { Provider } from "../context";
// import "antd/dist/antd.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ToastContainer position="top-center" />
          <TopNav />
          <AntdRegistry>
            {children}
          </AntdRegistry>
        </Provider>
      </body>
    </html>
  );
}



